@startuml

actor user
actor admin
actor cloudStorage
actor disk

package hlogger {
  user <-right--> (view logs)
  admin -right-> (authorized users): adds
  user <--> (download logs)
  (view logs) -[hidden]-> (download logs)
  (view logs) --> (authorized users): verifies
  (download logs) --> (authorized users): verifies
  (view logs) --> (cached reader)
  (download logs) -[norank]-> (cached reader)
  (cached reader) -up-> cloudStorage
  (cached reader) -down-> disk
}

disk -[hidden]up-> cloudStorage
admin -[hidden]up-> user

@enduml